name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Install Go
      if: success()
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: go test
